networks:
  proxy-net:
    driver: bridge
  internal-net:
    driver: bridge
    internal: true

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  application:
    image: ${IMAGE_URL}
    container_name: app-${SERVICE}
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 2048M
    environment:
      - STASH_STASH=/data
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_CONFIG_FILE=/config/config.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./${SERVICE}-data/config:/config
      - ./${SERVICE}-data/metadata:/metadata
      - ./${SERVICE}-data/cache:/cache
      - ./${SERVICE}-data/blobs:/blobs
      - ./${SERVICE}-data/generated:/generated
      - ${STASH_MEDIA_PATH}:/data
    logging: *default-logging
    networks:
      - proxy-net